# reunite:
  # ignoreLint: true
  # ignoreLinkChecker: true
extends:
  - recommended

apis:
  accounting-reports:
    root: ./apis/accounting-reports-final.yaml

links:
  - href: https://fonts.googleapis.com/css2?family=VT323&display=swap
  - href: https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap

navbar:
  items:
    - group: API Reference
      items:
        - page: apis/accounting-reports-final.yaml
          label: Accounting Reports
    - group: Guides
    - group: Resources
      items: 
        - page: guides/resources-overview.page.tsx
          label: Resources Overview
        - page: guides/authorization-code-flow.md
          label: Authorization Code Flow
        - page: guides/rate-limiting.md
          label: Rate Limiting
        - page: guides/refresh-tokens.md
          label: Refresh Token    
    - page: tools/index.md
      label: Tools
    - page: changelog.md
      label: Changelog
    - page: about.md
      label: About this template



mockServer:
  off: true 

markdown:
  toc:
    depth: 2
logo:
  image: images/logo.svg
  link: /
footer:
  copyrightText: Copyleft © Redocly Inc. No rights reserved.
sso:
  - GUEST
#rbac:
#  content:
#    '/apis/*':
#      authenticated: read


openapi: 
  layout: 'three-panel'
  codeSamples: 
      languages: 
      - lang: 'curl'
        label: 'cURL'
      - lang: 'C#'
        label: 'C#'
      - lang: 'Python'
        label: 'Python'
      - lang: 'JavaScript'
        label: 'JavaScript'
  hideSchemaTitles: true
  hideReplay: true



